### ISSUE TITLE
ReferenceError: vjs is not defined on VJS 4.6.1

### ISSUE THREAD

**Issue by Globulopolis** [mickey/videojs-progressTips#1]
Plugin isn't working with the new version. It's throw an error

> "ReferenceError: vjs is not defined"
> on line  vjs.plugin('progressTips', function(options) {

**Comment by adamtal3** [comment]
Fixed the plugin to work with videojs 4.6.4:
https://github.com/adamtal3/videojs-progressTips

It does has an issue though when using the video.js and not video.dev.js because the minification changed the name of "techName".

**Comment by mickey** [comment]
It should work with the last version, see the last [PR](https://github.com/mickey/videojs-progressTips/pull/3) for details. Thanks @adamtal3
